/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'studentId' : StudentId,
  'present' : boolean,
  'date' : bigint,
}
export type ClassId = bigint;
export interface FeeRecord {
  'studentId' : StudentId,
  'isPaid' : boolean,
  'classId' : ClassId,
  'amount' : bigint,
}
export interface MonthlyAttendanceSummary {
  'month' : bigint,
  'studentId' : StudentId,
  'totalDays' : bigint,
  'daysAbsent' : bigint,
  'daysPresent' : bigint,
}
export interface ReportCard {
  'id' : ReportCardId,
  'subjectMarks' : Array<SubjectMarks>,
  'teacherRemarks' : string,
  'totalMarks' : bigint,
  'studentId' : StudentId,
  'grade' : string,
  'teacherId' : TeacherId,
  'evaluationDate' : bigint,
}
export type ReportCardId = bigint;
export interface Student {
  'id' : StudentId,
  'parentContact' : string,
  'name' : string,
  'photoUrl' : [] | [string],
  'classId' : ClassId,
  'admissionStatus' : boolean,
}
export type StudentId = bigint;
export interface SubjectMarks { 'marks' : bigint, 'subject' : string }
export type TeacherId = bigint;
export interface TeacherProfile {
  'id' : TeacherId,
  'subject' : string,
  'name' : string,
  'uniqueId' : string,
  'assignedClasses' : Array<ClassId>,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFeeRecord' : ActorMethod<[StudentId, ClassId, bigint, boolean], bigint>,
  'addReportCard' : ActorMethod<
    [StudentId, TeacherId, Array<SubjectMarks>, bigint, string, string, bigint],
    ReportCardId
  >,
  'addStudent' : ActorMethod<
    [string, ClassId, string, boolean, [] | [string]],
    StudentId
  >,
  'addTeacherWithCredentials' : ActorMethod<
    [string, string, Array<ClassId>, string, string],
    TeacherId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignTeacherRole' : ActorMethod<[Principal, string], undefined>,
  'deleteFeeRecord' : ActorMethod<[bigint], undefined>,
  'deleteStudent' : ActorMethod<[StudentId], undefined>,
  'deleteTeacher' : ActorMethod<[TeacherId], undefined>,
  'getAllAttendance' : ActorMethod<[], Array<AttendanceRecord>>,
  'getAllFeeRecords' : ActorMethod<[], Array<FeeRecord>>,
  'getAllReportCards' : ActorMethod<[], Array<ReportCard>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTeachers' : ActorMethod<[], Array<TeacherProfile>>,
  'getAttendanceByStudent' : ActorMethod<[StudentId], Array<AttendanceRecord>>,
  'getCallerRole' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardMetrics' : ActorMethod<
    [],
    {
      'totalFeesCollected' : bigint,
      'totalStudents' : bigint,
      'outstandingFees' : bigint,
      'totalTeachers' : bigint,
    }
  >,
  'getFeeRecord' : ActorMethod<[bigint], [] | [FeeRecord]>,
  'getFeeRecordsByClass' : ActorMethod<[ClassId], Array<FeeRecord>>,
  'getFeeRecordsByStudent' : ActorMethod<[StudentId], Array<FeeRecord>>,
  'getMonthlyAttendanceSummary' : ActorMethod<
    [StudentId, bigint],
    Array<MonthlyAttendanceSummary>
  >,
  'getMonthlyAttendanceSummaryAllStudents' : ActorMethod<
    [bigint],
    Array<MonthlyAttendanceSummary>
  >,
  'getReportCard' : ActorMethod<[ReportCardId], [] | [ReportCard]>,
  'getReportCardsByClass' : ActorMethod<[ClassId], Array<ReportCard>>,
  'getReportCardsByStudent' : ActorMethod<[StudentId], Array<ReportCard>>,
  'getReportCardsByTeacher' : ActorMethod<[TeacherId], Array<ReportCard>>,
  'getStudent' : ActorMethod<[StudentId], [] | [Student]>,
  'getStudentsByClass' : ActorMethod<[ClassId], Array<Student>>,
  'getTeacher' : ActorMethod<[TeacherId], [] | [TeacherProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAttendance' : ActorMethod<[StudentId, bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFeeRecord' : ActorMethod<
    [bigint, StudentId, ClassId, bigint, boolean],
    undefined
  >,
  'updateReportCard' : ActorMethod<
    [
      ReportCardId,
      StudentId,
      TeacherId,
      Array<SubjectMarks>,
      bigint,
      string,
      string,
      bigint,
    ],
    undefined
  >,
  'updateStudent' : ActorMethod<
    [StudentId, string, ClassId, string, boolean, [] | [string]],
    undefined
  >,
  'updateTeacher' : ActorMethod<
    [TeacherId, string, string, Array<ClassId>],
    undefined
  >,
  'verifyAndAuthenticateTeacher' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];