/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const StudentId = IDL.Nat;
export const ClassId = IDL.Nat;
export const TeacherId = IDL.Nat;
export const SubjectMarks = IDL.Record({
  'marks' : IDL.Nat,
  'subject' : IDL.Text,
});
export const ReportCardId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActivityAuditLogEntry = IDL.Record({
  'action' : IDL.Text,
  'performerRole' : IDL.Text,
  'performerPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const AttendanceRecord = IDL.Record({
  'studentId' : StudentId,
  'present' : IDL.Bool,
  'date' : IDL.Int,
});
export const FeeRecord = IDL.Record({
  'studentId' : StudentId,
  'isPaid' : IDL.Bool,
  'classId' : ClassId,
  'amount' : IDL.Nat,
});
export const ReportCard = IDL.Record({
  'id' : ReportCardId,
  'subjectMarks' : IDL.Vec(SubjectMarks),
  'teacherRemarks' : IDL.Text,
  'totalMarks' : IDL.Nat,
  'studentId' : StudentId,
  'grade' : IDL.Text,
  'teacherId' : TeacherId,
  'evaluationDate' : IDL.Int,
});
export const Student = IDL.Record({
  'id' : StudentId,
  'parentContact' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'classId' : ClassId,
  'admissionStatus' : IDL.Bool,
});
export const TeacherProfile = IDL.Record({
  'id' : TeacherId,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'uniqueId' : IDL.Text,
  'assignedClasses' : IDL.Vec(ClassId),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const MonthlyAttendanceSummary = IDL.Record({
  'month' : IDL.Nat,
  'studentId' : StudentId,
  'totalDays' : IDL.Nat,
  'daysAbsent' : IDL.Nat,
  'daysPresent' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFeeRecord' : IDL.Func(
      [StudentId, ClassId, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addReportCard' : IDL.Func(
      [
        StudentId,
        TeacherId,
        IDL.Vec(SubjectMarks),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [ReportCardId],
      [],
    ),
  'addStudent' : IDL.Func(
      [IDL.Text, ClassId, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [StudentId],
      [],
    ),
  'addTeacherWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(ClassId), IDL.Text, IDL.Text],
      [TeacherId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignTeacherRole' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'createActivityLogEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteFeeRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteStudent' : IDL.Func([StudentId], [], []),
  'deleteTeacher' : IDL.Func([TeacherId], [], []),
  'getActivityAuditLogsByRole' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ActivityAuditLogEntry)],
      ['query'],
    ),
  'getAllActivityAuditLogs' : IDL.Func(
      [],
      [IDL.Vec(ActivityAuditLogEntry)],
      ['query'],
    ),
  'getAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
  'getAllFeeRecords' : IDL.Func([], [IDL.Vec(FeeRecord)], ['query']),
  'getAllReportCards' : IDL.Func([], [IDL.Vec(ReportCard)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
  'getAttendanceByStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalFeesCollected' : IDL.Nat,
          'totalStudents' : IDL.Nat,
          'outstandingFees' : IDL.Nat,
          'totalTeachers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getFeeRecord' : IDL.Func([IDL.Nat], [IDL.Opt(FeeRecord)], ['query']),
  'getFeeRecordsByClass' : IDL.Func([ClassId], [IDL.Vec(FeeRecord)], ['query']),
  'getFeeRecordsByStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(FeeRecord)],
      ['query'],
    ),
  'getMonthlyAttendanceSummary' : IDL.Func(
      [StudentId, IDL.Nat],
      [IDL.Vec(MonthlyAttendanceSummary)],
      ['query'],
    ),
  'getMonthlyAttendanceSummaryAllStudents' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MonthlyAttendanceSummary)],
      ['query'],
    ),
  'getReportCard' : IDL.Func([ReportCardId], [IDL.Opt(ReportCard)], ['query']),
  'getReportCardsByClass' : IDL.Func(
      [ClassId],
      [IDL.Vec(ReportCard)],
      ['query'],
    ),
  'getReportCardsByStudent' : IDL.Func(
      [StudentId],
      [IDL.Vec(ReportCard)],
      ['query'],
    ),
  'getReportCardsByTeacher' : IDL.Func(
      [TeacherId],
      [IDL.Vec(ReportCard)],
      ['query'],
    ),
  'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
  'getStudentActivityHistory' : IDL.Func(
      [StudentId],
      [IDL.Vec(ActivityAuditLogEntry)],
      ['query'],
    ),
  'getStudentsByClass' : IDL.Func([ClassId], [IDL.Vec(Student)], ['query']),
  'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(TeacherProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAttendance' : IDL.Func([StudentId, IDL.Int, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleFeePaymentStatus' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'updateFeeRecord' : IDL.Func(
      [IDL.Nat, StudentId, ClassId, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateReportCard' : IDL.Func(
      [
        ReportCardId,
        StudentId,
        TeacherId,
        IDL.Vec(SubjectMarks),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Int,
      ],
      [],
      [],
    ),
  'updateStudent' : IDL.Func(
      [StudentId, IDL.Text, ClassId, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updateTeacher' : IDL.Func(
      [TeacherId, IDL.Text, IDL.Text, IDL.Vec(ClassId)],
      [],
      [],
    ),
  'verifyAndAuthenticateTeacher' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const StudentId = IDL.Nat;
  const ClassId = IDL.Nat;
  const TeacherId = IDL.Nat;
  const SubjectMarks = IDL.Record({ 'marks' : IDL.Nat, 'subject' : IDL.Text });
  const ReportCardId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActivityAuditLogEntry = IDL.Record({
    'action' : IDL.Text,
    'performerRole' : IDL.Text,
    'performerPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const AttendanceRecord = IDL.Record({
    'studentId' : StudentId,
    'present' : IDL.Bool,
    'date' : IDL.Int,
  });
  const FeeRecord = IDL.Record({
    'studentId' : StudentId,
    'isPaid' : IDL.Bool,
    'classId' : ClassId,
    'amount' : IDL.Nat,
  });
  const ReportCard = IDL.Record({
    'id' : ReportCardId,
    'subjectMarks' : IDL.Vec(SubjectMarks),
    'teacherRemarks' : IDL.Text,
    'totalMarks' : IDL.Nat,
    'studentId' : StudentId,
    'grade' : IDL.Text,
    'teacherId' : TeacherId,
    'evaluationDate' : IDL.Int,
  });
  const Student = IDL.Record({
    'id' : StudentId,
    'parentContact' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'classId' : ClassId,
    'admissionStatus' : IDL.Bool,
  });
  const TeacherProfile = IDL.Record({
    'id' : TeacherId,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'uniqueId' : IDL.Text,
    'assignedClasses' : IDL.Vec(ClassId),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const MonthlyAttendanceSummary = IDL.Record({
    'month' : IDL.Nat,
    'studentId' : StudentId,
    'totalDays' : IDL.Nat,
    'daysAbsent' : IDL.Nat,
    'daysPresent' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFeeRecord' : IDL.Func(
        [StudentId, ClassId, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addReportCard' : IDL.Func(
        [
          StudentId,
          TeacherId,
          IDL.Vec(SubjectMarks),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [ReportCardId],
        [],
      ),
    'addStudent' : IDL.Func(
        [IDL.Text, ClassId, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [StudentId],
        [],
      ),
    'addTeacherWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(ClassId), IDL.Text, IDL.Text],
        [TeacherId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignTeacherRole' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'createActivityLogEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteFeeRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteStudent' : IDL.Func([StudentId], [], []),
    'deleteTeacher' : IDL.Func([TeacherId], [], []),
    'getActivityAuditLogsByRole' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ActivityAuditLogEntry)],
        ['query'],
      ),
    'getAllActivityAuditLogs' : IDL.Func(
        [],
        [IDL.Vec(ActivityAuditLogEntry)],
        ['query'],
      ),
    'getAllAttendance' : IDL.Func([], [IDL.Vec(AttendanceRecord)], ['query']),
    'getAllFeeRecords' : IDL.Func([], [IDL.Vec(FeeRecord)], ['query']),
    'getAllReportCards' : IDL.Func([], [IDL.Vec(ReportCard)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
    'getAttendanceByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerRole' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalFeesCollected' : IDL.Nat,
            'totalStudents' : IDL.Nat,
            'outstandingFees' : IDL.Nat,
            'totalTeachers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getFeeRecord' : IDL.Func([IDL.Nat], [IDL.Opt(FeeRecord)], ['query']),
    'getFeeRecordsByClass' : IDL.Func(
        [ClassId],
        [IDL.Vec(FeeRecord)],
        ['query'],
      ),
    'getFeeRecordsByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(FeeRecord)],
        ['query'],
      ),
    'getMonthlyAttendanceSummary' : IDL.Func(
        [StudentId, IDL.Nat],
        [IDL.Vec(MonthlyAttendanceSummary)],
        ['query'],
      ),
    'getMonthlyAttendanceSummaryAllStudents' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MonthlyAttendanceSummary)],
        ['query'],
      ),
    'getReportCard' : IDL.Func(
        [ReportCardId],
        [IDL.Opt(ReportCard)],
        ['query'],
      ),
    'getReportCardsByClass' : IDL.Func(
        [ClassId],
        [IDL.Vec(ReportCard)],
        ['query'],
      ),
    'getReportCardsByStudent' : IDL.Func(
        [StudentId],
        [IDL.Vec(ReportCard)],
        ['query'],
      ),
    'getReportCardsByTeacher' : IDL.Func(
        [TeacherId],
        [IDL.Vec(ReportCard)],
        ['query'],
      ),
    'getStudent' : IDL.Func([StudentId], [IDL.Opt(Student)], ['query']),
    'getStudentActivityHistory' : IDL.Func(
        [StudentId],
        [IDL.Vec(ActivityAuditLogEntry)],
        ['query'],
      ),
    'getStudentsByClass' : IDL.Func([ClassId], [IDL.Vec(Student)], ['query']),
    'getTeacher' : IDL.Func([TeacherId], [IDL.Opt(TeacherProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAttendance' : IDL.Func([StudentId, IDL.Int, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleFeePaymentStatus' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'updateFeeRecord' : IDL.Func(
        [IDL.Nat, StudentId, ClassId, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'updateReportCard' : IDL.Func(
        [
          ReportCardId,
          StudentId,
          TeacherId,
          IDL.Vec(SubjectMarks),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Int,
        ],
        [],
        [],
      ),
    'updateStudent' : IDL.Func(
        [StudentId, IDL.Text, ClassId, IDL.Text, IDL.Bool, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updateTeacher' : IDL.Func(
        [TeacherId, IDL.Text, IDL.Text, IDL.Vec(ClassId)],
        [],
        [],
      ),
    'verifyAndAuthenticateTeacher' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };